// This file was automatically generated by Java-GI. Do not edit this file
// directly! Visit <https://java-gi.org> for more information.
//
// The API documentation in this file was derived from GObject-Introspection
// metadata and may include text or comments from the original C sources.
//
// Copyright (c), upstream authors of the GObject-Introspection data.
//
// This generated file is distributed under the same license as the original
// GObject-Introspection data, unless otherwise specified. Users of this file
// are responsible for complying with any licenses or terms required by the
// original authors.
//
// THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
//
package goa;

import java.lang.Deprecated;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;
import org.gnome.gio.DBusInterfaceInfo;
import org.gnome.glib.Type;
import org.gnome.gobject.GObject;
import org.gnome.gobject.TypeInterface;
import org.javagi.base.Proxy;
import org.javagi.interop.Interop;
import org.javagi.interop.MemoryCleaner;

/**
 * Abstract interface type for the D-Bus interface &lt;link linkend="gdbus-interface-org-gnome-OnlineAccounts-Maps.top_of_page"&gt;org.gnome.OnlineAccounts.Maps&lt;/link&gt;.
 *
 * @since 3.14.0
 * @deprecated The D-Bus interface has been deprecated.
 */
@Generated("io.github.jwharm.JavaGI")
@Deprecated
public interface Maps extends Proxy {
    /**
     * Get the GType of the Maps class
     *
     * @return the GType
     */
    static Type getType() {
        return Interop.getType("goa_maps_get_type");
    }

    /**
     * Gets a machine-readable description of the &lt;link linkend="gdbus-interface-org-gnome-OnlineAccounts-Maps.top_of_page"&gt;org.gnome.OnlineAccounts.Maps&lt;/link&gt; D-Bus interface.
     *
     * @return A {@code GDBusInterfaceInfo}. Do not free.
     * @since 3.14.0
     * @deprecated The D-Bus interface has been deprecated.
     */
    @Deprecated
    static DBusInterfaceInfo interfaceInfo() {
        MemorySegment _result;
        try {
            _result = (MemorySegment) MapsMethodHandles.goa_maps_interface_info.invokeExact();
        } catch (Throwable _err) {
            throw new AssertionError(_err);
        }
        if (_result == null || _result.equals(MemorySegment.NULL)) {
            return null;
        }
        DBusInterfaceInfo _returnValue = MemorySegment.NULL.equals(_result) ? null : new DBusInterfaceInfo(_result);
        if (_returnValue != null) {
            _returnValue = _returnValue.ref();
            MemoryCleaner.takeOwnership(_returnValue);
            MemoryCleaner.setFreeFunc(_returnValue, "g_dbus_interface_info_unref");
        }
        return _returnValue;
    }

    /**
     * Overrides all {@code GObject} properties in the {@code GoaMaps} interface for a concrete class.
     * The properties are overridden in the order they are defined.
     *
     * @param klass The class structure for a {@code GObject} derived class.
     * @param propertyIdBegin The property id to assign to the first overridden property.
     * @return The last property id.
     * @since 3.14.0
     * @deprecated The D-Bus interface has been deprecated.
     */
    @Deprecated
    static int overrideProperties(GObject.ObjectClass klass, int propertyIdBegin) {
        int _result;
        try {
            _result = (int) MapsMethodHandles.goa_maps_override_properties.invokeExact(
                    (MemorySegment) (klass == null ? MemorySegment.NULL : klass.handle()), 
                    propertyIdBegin);
        } catch (Throwable _err) {
            throw new AssertionError(_err);
        }
        int _returnValue = _result;
        return _returnValue;
    }

    /**
     * The Maps$Impl type represents a native instance of the Maps interface.
     */
    class Maps$Impl extends GObject implements Maps {
        static {
            Goa.javagi$ensureInitialized();
        }

        /**
         * Creates a new instance of Maps for the provided memory address.
         *
         * @param address the memory address of the instance
         */
        public Maps$Impl(MemorySegment address) {
            super(address);
        }
    }

    /**
     * Virtual table for the D-Bus interface &lt;link linkend="gdbus-interface-org-gnome-OnlineAccounts-Maps.top_of_page"&gt;org.gnome.OnlineAccounts.Maps&lt;/link&gt;.
     *
     * @since 3.14.0
     * @deprecated The D-Bus interface has been deprecated.
     */
    @Deprecated
    class MapsIface extends TypeInterface {
        /**
         * Create a MapsIface proxy instance for the provided memory address.
         *
         * @param address the memory address of the native object
         */
        public MapsIface(MemorySegment address) {
            super(Interop.reinterpret(address, getMemoryLayout().byteSize()));
        }

        /**
         * The memory layout of the native struct.
         *
         * @return the memory layout
         */
        public static MemoryLayout getMemoryLayout() {
            return MemoryLayout.structLayout(
                TypeInterface.getMemoryLayout().withName("parent_iface")
            ).withName("GoaMapsIface");
        }
    }
}
