// This file was automatically generated by Java-GI. Do not edit this file
// directly! Visit <https://java-gi.org> for more information.
//
// The API documentation in this file was derived from GObject-Introspection
// metadata and may include text or comments from the original C sources.
//
// Copyright (c), upstream authors of the GObject-Introspection data.
//
// This generated file is distributed under the same license as the original
// GObject-Introspection data, unless otherwise specified. Users of this file
// are responsible for complying with any licenses or terms required by the
// original authors.
//
// THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
//
package goa;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import javax.annotation.processing.Generated;
import org.gnome.gio.DBusInterface;
import org.gnome.gio.DBusInterfaceSkeleton;
import org.gnome.glib.Type;
import org.gnome.gobject.GObject;
import org.gnome.gobject.Value;
import org.javagi.gobject.InstanceCache;
import org.javagi.gobject.types.TypeCache;
import org.javagi.interop.Interop;

/**
 * The {@code GoaOAuth2BasedSkeleton} structure contains only private data and should only be accessed using the provided API.
 */
@Generated("io.github.jwharm.JavaGI")
public class OAuth2BasedSkeleton extends DBusInterfaceSkeleton implements DBusInterface, OAuth2Based {
    static {
        Goa.javagi$ensureInitialized();
    }

    /**
     * Create a OAuth2BasedSkeleton proxy instance for the provided memory address.
     *
     * @param address the memory address of the native object
     */
    public OAuth2BasedSkeleton(MemorySegment address) {
        super(Interop.reinterpret(address, getMemoryLayout().byteSize()));
    }

    /**
     * Creates a new OAuth2BasedSkeleton.
     */
    public OAuth2BasedSkeleton() {
        super((MemorySegment) null);
        InstanceCache.newGObject(this, TypeCache.getType(this.getClass()), getMemoryLayout().byteSize(), (Object[]) null);
    }

    /**
     * Get the GType of the OAuth2BasedSkeleton class
     *
     * @return the GType
     */
    public static Type getType() {
        return Interop.getType("goa_oauth2_based_skeleton_get_type");
    }

    /**
     * The memory layout of the native struct.
     *
     * @return the memory layout
     */
    public static MemoryLayout getMemoryLayout() {
        return MemoryLayout.structLayout(
            DBusInterfaceSkeleton.getMemoryLayout().withName("parent_instance"),
            ValueLayout.ADDRESS.withName("priv")
        ).withName("GoaOAuth2BasedSkeleton");
    }

    /**
     * Returns this instance as if it were its parent type. This is mostly
     * synonymous to the Java {@code super} keyword, but will set the native
     * typeclass function pointers to the parent type. When overriding a native
     * virtual method in Java, "chaining up" with {@code super.methodName()}
     * doesn't work, because it invokes the overridden function pointer again.
     * To chain up, call {@code asParent().methodName()}. This will call the
     * native function pointer of this virtual method in the typeclass of the
     * parent type.
     */
    protected OAuth2BasedSkeleton asParent() {
        OAuth2BasedSkeleton _parent = new OAuth2BasedSkeleton(handle());
        _parent.callParent(true);
        return _parent;
    }

    /**
     * A {@link Builder} object constructs a {@code OAuth2BasedSkeleton}
     * with the specified properties.
     * Use the various {@code set...()} methods to set properties,
     * and finish construction with {@link Builder#build()}.
     *
     * @return the builder object
     */
    public static Builder<? extends Builder> builder() {
        return new Builder<>();
    }

    /**
     * Class structure for {@code GoaOAuth2BasedSkeleton}.
     */
    public static class OAuth2BasedSkeletonClass extends DBusInterfaceSkeleton.DBusInterfaceSkeletonClass {
        /**
         * Create a OAuth2BasedSkeletonClass proxy instance for the provided memory address.
         *
         * @param address the memory address of the native object
         */
        public OAuth2BasedSkeletonClass(MemorySegment address) {
            super(Interop.reinterpret(address, getMemoryLayout().byteSize()));
        }

        /**
         * The memory layout of the native struct.
         *
         * @return the memory layout
         */
        public static MemoryLayout getMemoryLayout() {
            return MemoryLayout.structLayout(
                DBusInterfaceSkeleton.DBusInterfaceSkeletonClass.getMemoryLayout().withName("parent_class")
            ).withName("GoaOAuth2BasedSkeletonClass");
        }
    }

    /**
     * Inner class implementing a builder pattern to construct a GObject with
     * properties.
     *
     * @param <B> the type of the Builder that is returned
     */
    public static class Builder<B extends Builder<B>> extends DBusInterfaceSkeleton.Builder<B> implements OAuth2Based.Builder<B> {
        /**
         * Default constructor for a {@code Builder} object.
         */
        protected Builder() {
        }

        /**
         * Finish building the {@code OAuth2BasedSkeleton} object. This will call
         * {@link GObject#withProperties} to create a new GObject instance,
         * which is then cast to {@code OAuth2BasedSkeleton}.
         *
         * @return a new instance of {@code OAuth2BasedSkeleton} with the properties
         *         that were set in the Builder object.
         */
        public OAuth2BasedSkeleton build() {
            try {
                var _instance = (OAuth2BasedSkeleton) GObject.withProperties(OAuth2BasedSkeleton.getType(), getNames(), getValues());
                connectSignals(_instance.handle());
                return _instance;
            } finally {
                for (Value _value : getValues()) _value.unset();
                getArena().close();
            }
        }
    }
}
