// This file was automatically generated by Java-GI. Do not edit this file
// directly! Visit <https://java-gi.org> for more information.
//
// The API documentation in this file was derived from GObject-Introspection
// metadata and may include text or comments from the original C sources.
//
// Copyright (c), upstream authors of the GObject-Introspection data.
//
// This generated file is distributed under the same license as the original
// GObject-Introspection data, unless otherwise specified. Users of this file
// are responsible for complying with any licenses or terms required by the
// original authors.
//
// THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
//
package goa;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import javax.annotation.processing.Generated;
import org.javagi.interop.Interop;

@Generated("io.github.jwharm.JavaGI")
final class OAuthBasedMethodHandles {
    static final MethodHandle goa_oauth_based_interface_info = Interop.downcallHandle(
            "goa_oauth_based_interface_info", FunctionDescriptor.of(ValueLayout.ADDRESS), false);

    static final MethodHandle goa_oauth_based_override_properties = Interop.downcallHandle(
            "goa_oauth_based_override_properties", FunctionDescriptor.of(ValueLayout.JAVA_INT,
            ValueLayout.ADDRESS, ValueLayout.JAVA_INT), false);

    static final MethodHandle goa_oauth_based_call_get_access_token = Interop.downcallHandle(
            "goa_oauth_based_call_get_access_token", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS), false);

    static final MethodHandle goa_oauth_based_call_get_access_token_finish = Interop.downcallHandle(
            "goa_oauth_based_call_get_access_token_finish",
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS),
            false);

    static final MethodHandle goa_oauth_based_call_get_access_token_sync = Interop.downcallHandle(
            "goa_oauth_based_call_get_access_token_sync",
            FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS),
            false);

    static final MethodHandle goa_oauth_based_complete_get_access_token = Interop.downcallHandle(
            "goa_oauth_based_complete_get_access_token",
            FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.JAVA_INT), false);

    static final MethodHandle goa_oauth_based_dup_consumer_key = Interop.downcallHandle(
            "goa_oauth_based_dup_consumer_key", FunctionDescriptor.of(ValueLayout.ADDRESS,
            ValueLayout.ADDRESS), false);

    static final MethodHandle goa_oauth_based_dup_consumer_secret = Interop.downcallHandle(
            "goa_oauth_based_dup_consumer_secret", FunctionDescriptor.of(ValueLayout.ADDRESS,
            ValueLayout.ADDRESS), false);

    static final MethodHandle goa_oauth_based_get_consumer_key = Interop.downcallHandle(
            "goa_oauth_based_get_consumer_key", FunctionDescriptor.of(ValueLayout.ADDRESS,
            ValueLayout.ADDRESS), false);

    static final MethodHandle goa_oauth_based_get_consumer_secret = Interop.downcallHandle(
            "goa_oauth_based_get_consumer_secret", FunctionDescriptor.of(ValueLayout.ADDRESS,
            ValueLayout.ADDRESS), false);

    static final MethodHandle goa_oauth_based_set_consumer_key = Interop.downcallHandle(
            "goa_oauth_based_set_consumer_key", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS,
            ValueLayout.ADDRESS), false);

    static final MethodHandle goa_oauth_based_set_consumer_secret = Interop.downcallHandle(
            "goa_oauth_based_set_consumer_secret", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS,
            ValueLayout.ADDRESS), false);
}
