// This file was automatically generated by Java-GI. Do not edit this file
// directly! Visit <https://java-gi.org> for more information.
//
// The API documentation in this file was derived from GObject-Introspection
// metadata and may include text or comments from the original C sources.
//
// Copyright (c), upstream authors of the GObject-Introspection data.
//
// This generated file is distributed under the same license as the original
// GObject-Introspection data, unless otherwise specified. Users of this file
// are responsible for complying with any licenses or terms required by the
// original authors.
//
// THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
//
package goa;

import java.lang.Boolean;
import java.lang.FunctionalInterface;
import java.lang.String;
import java.lang.Throwable;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import javax.annotation.processing.Generated;
import org.gnome.gio.AsyncReadyCallback;
import org.gnome.gio.AsyncResult;
import org.gnome.gio.Cancellable;
import org.gnome.gio.DBusInterfaceInfo;
import org.gnome.gio.DBusMethodInvocation;
import org.gnome.glib.GLib;
import org.gnome.glib.LogLevelFlags;
import org.gnome.glib.Type;
import org.gnome.glib.Variant;
import org.gnome.gobject.GObject;
import org.gnome.gobject.TypeInterface;
import org.javagi.base.Constants;
import org.javagi.base.FunctionPointer;
import org.javagi.base.GErrorException;
import org.javagi.base.Out;
import org.javagi.base.Proxy;
import org.javagi.base.TransferOwnership;
import org.javagi.gobject.InstanceCache;
import org.javagi.gobject.SignalConnection;
import org.javagi.gobject.types.Signals;
import org.javagi.interop.ArenaCloseAction;
import org.javagi.interop.Arenas;
import org.javagi.interop.Interop;
import org.javagi.interop.MemoryCleaner;
import org.jetbrains.annotations.Nullable;

/**
 * Abstract interface type for the D-Bus interface &lt;link linkend="gdbus-interface-org-gnome-OnlineAccounts-Manager.top_of_page"&gt;org.gnome.OnlineAccounts.Manager&lt;/link&gt;.
 */
@Generated("io.github.jwharm.JavaGI")
public interface Manager extends Proxy {
    /**
     * Get the GType of the Manager class
     *
     * @return the GType
     */
    static Type getType() {
        return Interop.getType("goa_manager_get_type");
    }

    /**
     * Gets a machine-readable description of the &lt;link linkend="gdbus-interface-org-gnome-OnlineAccounts-Manager.top_of_page"&gt;org.gnome.OnlineAccounts.Manager&lt;/link&gt; D-Bus interface.
     *
     * @return A {@code GDBusInterfaceInfo}. Do not free.
     */
    static DBusInterfaceInfo interfaceInfo() {
        MemorySegment _result;
        try {
            _result = (MemorySegment) ManagerMethodHandles.goa_manager_interface_info.invokeExact();
        } catch (Throwable _err) {
            throw new AssertionError(_err);
        }
        if (_result == null || _result.equals(MemorySegment.NULL)) {
            return null;
        }
        DBusInterfaceInfo _returnValue = MemorySegment.NULL.equals(_result) ? null : new DBusInterfaceInfo(_result);
        if (_returnValue != null) {
            _returnValue = _returnValue.ref();
            MemoryCleaner.takeOwnership(_returnValue);
            MemoryCleaner.setFreeFunc(_returnValue, "g_dbus_interface_info_unref");
        }
        return _returnValue;
    }

    /**
     * Overrides all {@code GObject} properties in the {@code GoaManager} interface for a concrete class.
     * The properties are overridden in the order they are defined.
     *
     * @param klass The class structure for a {@code GObject} derived class.
     * @param propertyIdBegin The property id to assign to the first overridden property.
     * @return The last property id.
     */
    static int overrideProperties(GObject.ObjectClass klass, int propertyIdBegin) {
        int _result;
        try {
            _result = (int) ManagerMethodHandles.goa_manager_override_properties.invokeExact(
                    (MemorySegment) (klass == null ? MemorySegment.NULL : klass.handle()), 
                    propertyIdBegin);
        } catch (Throwable _err) {
            throw new AssertionError(_err);
        }
        int _returnValue = _result;
        return _returnValue;
    }

    /**
     * Asynchronously invokes the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.AddAccount"&gt;AddAccount()&lt;/link&gt; D-Bus method on {@code proxy.}
     * When the operation is finished, {@code callback} will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
     * You can then call goa_manager_call_add_account_finish() to get the result of the operation.
     * <p>
     * See goa_manager_call_add_account_sync() for the synchronous, blocking version of this method.
     *
     * @param argProvider Argument to pass with the method invocation.
     * @param argIdentity Argument to pass with the method invocation.
     * @param argPresentationIdentity Argument to pass with the method invocation.
     * @param argCredentials Argument to pass with the method invocation.
     * @param argDetails Argument to pass with the method invocation.
     * @param cancellable A {@code GCancellable} or {@code null}.
     * @param callback A {@code GAsyncReadyCallback} to call when the request is satisfied or {@code null}.
     */
    default void callAddAccount(String argProvider, String argIdentity,
            String argPresentationIdentity, Variant argCredentials, Variant argDetails,
            @Nullable Cancellable cancellable, @Nullable AsyncReadyCallback callback) {
        try (var _arena = Arena.ofConfined()) {
            final Arena _callbackScope = Arena.ofShared();
            if (callback != null) ArenaCloseAction.CLEANER.register(callback, new ArenaCloseAction(_callbackScope));
            try {
                ManagerMethodHandles.goa_manager_call_add_account.invokeExact(handle(), 
                        (MemorySegment) (argProvider == null ? MemorySegment.NULL : Interop.allocateNativeString(argProvider, _arena)), 
                        (MemorySegment) (argIdentity == null ? MemorySegment.NULL : Interop.allocateNativeString(argIdentity, _arena)), 
                        (MemorySegment) (argPresentationIdentity == null ? MemorySegment.NULL : Interop.allocateNativeString(argPresentationIdentity, _arena)), 
                        (MemorySegment) (argCredentials == null ? MemorySegment.NULL : argCredentials.handle()), 
                        (MemorySegment) (argDetails == null ? MemorySegment.NULL : argDetails.handle()), 
                        (MemorySegment) (cancellable == null ? MemorySegment.NULL : cancellable.handle()), 
                        (MemorySegment) (callback == null ? MemorySegment.NULL : callback.toCallback(_callbackScope)), 
                        MemorySegment.NULL);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
            Arenas.readyToClose(_callbackScope);
        }
    }

    /**
     * Finishes an operation started with goa_manager_call_add_account().
     *
     * @param outAccountObjectPath Return location for return parameter or {@code null} to ignore.
     * @param res The {@code GAsyncResult} obtained from the {@code GAsyncReadyCallback} passed to goa_manager_call_add_account().
     * @return {@code true} if the call succeeded, {@code false} if {@code error} is set.
     * @throws GErrorException see {@link org.gnome.glib.GError}
     */
    default boolean callAddAccountFinish(@Nullable Out<String> outAccountObjectPath,
            AsyncResult res) throws GErrorException {
        try (var _arena = Arena.ofConfined()) {
            MemorySegment _outAccountObjectPathPointer = _arena.allocate(ValueLayout.ADDRESS);
            MemorySegment _gerror = _arena.allocate(ValueLayout.ADDRESS);
            int _result;
            try {
                _result = (int) ManagerMethodHandles.goa_manager_call_add_account_finish.invokeExact(
                        handle(), 
                        (MemorySegment) (outAccountObjectPath == null ? MemorySegment.NULL : _outAccountObjectPathPointer), 
                        (MemorySegment) (res == null ? MemorySegment.NULL : res.handle()), _gerror);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
            if (GErrorException.isErrorSet(_gerror)) {
                throw new GErrorException(_gerror);
            }
            if (outAccountObjectPath != null) {
                outAccountObjectPath.set(Interop.getStringFrom(_outAccountObjectPathPointer.get(ValueLayout.ADDRESS, 0), TransferOwnership.FULL));
            }
            boolean _returnValue = _result != 0;
            return _returnValue;
        }
    }

    /**
     * Synchronously invokes the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.AddAccount"&gt;AddAccount()&lt;/link&gt; D-Bus method on {@code proxy.} The calling thread is blocked until a reply is received.
     * <p>
     * See goa_manager_call_add_account() for the asynchronous version of this method.
     *
     * @param argProvider Argument to pass with the method invocation.
     * @param argIdentity Argument to pass with the method invocation.
     * @param argPresentationIdentity Argument to pass with the method invocation.
     * @param argCredentials Argument to pass with the method invocation.
     * @param argDetails Argument to pass with the method invocation.
     * @param outAccountObjectPath Return location for return parameter or {@code null} to ignore.
     * @param cancellable A {@code GCancellable} or {@code null}.
     * @return {@code true} if the call succeeded, {@code false} if {@code error} is set.
     * @throws GErrorException see {@link org.gnome.glib.GError}
     */
    default boolean callAddAccountSync(String argProvider, String argIdentity,
            String argPresentationIdentity, Variant argCredentials, Variant argDetails,
            @Nullable Out<String> outAccountObjectPath, @Nullable Cancellable cancellable) throws
            GErrorException {
        try (var _arena = Arena.ofConfined()) {
            MemorySegment _outAccountObjectPathPointer = _arena.allocate(ValueLayout.ADDRESS);
            MemorySegment _gerror = _arena.allocate(ValueLayout.ADDRESS);
            int _result;
            try {
                _result = (int) ManagerMethodHandles.goa_manager_call_add_account_sync.invokeExact(
                        handle(), 
                        (MemorySegment) (argProvider == null ? MemorySegment.NULL : Interop.allocateNativeString(argProvider, _arena)), 
                        (MemorySegment) (argIdentity == null ? MemorySegment.NULL : Interop.allocateNativeString(argIdentity, _arena)), 
                        (MemorySegment) (argPresentationIdentity == null ? MemorySegment.NULL : Interop.allocateNativeString(argPresentationIdentity, _arena)), 
                        (MemorySegment) (argCredentials == null ? MemorySegment.NULL : argCredentials.handle()), 
                        (MemorySegment) (argDetails == null ? MemorySegment.NULL : argDetails.handle()), 
                        (MemorySegment) (outAccountObjectPath == null ? MemorySegment.NULL : _outAccountObjectPathPointer), 
                        (MemorySegment) (cancellable == null ? MemorySegment.NULL : cancellable.handle()), _gerror);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
            if (GErrorException.isErrorSet(_gerror)) {
                throw new GErrorException(_gerror);
            }
            if (outAccountObjectPath != null) {
                outAccountObjectPath.set(Interop.getStringFrom(_outAccountObjectPathPointer.get(ValueLayout.ADDRESS, 0), TransferOwnership.FULL));
            }
            boolean _returnValue = _result != 0;
            return _returnValue;
        }
    }

    /**
     * Asynchronously invokes the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.IsSupportedProvider"&gt;IsSupportedProvider()&lt;/link&gt; D-Bus method on {@code proxy.}
     * When the operation is finished, {@code callback} will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
     * You can then call goa_manager_call_is_supported_provider_finish() to get the result of the operation.
     * <p>
     * See goa_manager_call_is_supported_provider_sync() for the synchronous, blocking version of this method.
     *
     * @param argProviderType Argument to pass with the method invocation.
     * @param cancellable A {@code GCancellable} or {@code null}.
     * @param callback A {@code GAsyncReadyCallback} to call when the request is satisfied or {@code null}.
     */
    default void callIsSupportedProvider(String argProviderType, @Nullable Cancellable cancellable,
            @Nullable AsyncReadyCallback callback) {
        try (var _arena = Arena.ofConfined()) {
            final Arena _callbackScope = Arena.ofShared();
            if (callback != null) ArenaCloseAction.CLEANER.register(callback, new ArenaCloseAction(_callbackScope));
            try {
                ManagerMethodHandles.goa_manager_call_is_supported_provider.invokeExact(handle(), 
                        (MemorySegment) (argProviderType == null ? MemorySegment.NULL : Interop.allocateNativeString(argProviderType, _arena)), 
                        (MemorySegment) (cancellable == null ? MemorySegment.NULL : cancellable.handle()), 
                        (MemorySegment) (callback == null ? MemorySegment.NULL : callback.toCallback(_callbackScope)), 
                        MemorySegment.NULL);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
            Arenas.readyToClose(_callbackScope);
        }
    }

    /**
     * Finishes an operation started with goa_manager_call_is_supported_provider().
     *
     * @param outIsSupported Return location for return parameter or {@code null} to ignore.
     * @param res The {@code GAsyncResult} obtained from the {@code GAsyncReadyCallback} passed to goa_manager_call_is_supported_provider().
     * @return {@code true} if the call succeeded, {@code false} if {@code error} is set.
     * @throws GErrorException see {@link org.gnome.glib.GError}
     */
    default boolean callIsSupportedProviderFinish(@Nullable Out<Boolean> outIsSupported,
            AsyncResult res) throws GErrorException {
        try (var _arena = Arena.ofConfined()) {
            MemorySegment _outIsSupportedPointer = _arena.allocateFrom(
                    ValueLayout.JAVA_INT, Interop.toBoolean(outIsSupported) ? 1 : 0);
            MemorySegment _gerror = _arena.allocate(ValueLayout.ADDRESS);
            int _result;
            try {
                _result = (int) ManagerMethodHandles.goa_manager_call_is_supported_provider_finish.invokeExact(
                        handle(), 
                        (MemorySegment) (outIsSupported == null ? MemorySegment.NULL : _outIsSupportedPointer), 
                        (MemorySegment) (res == null ? MemorySegment.NULL : res.handle()), _gerror);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
            if (GErrorException.isErrorSet(_gerror)) {
                throw new GErrorException(_gerror);
            }
            if (outIsSupported != null) {
                outIsSupported.set(_outIsSupportedPointer.get(ValueLayout.JAVA_INT, 0) != 0);
            }
            boolean _returnValue = _result != 0;
            return _returnValue;
        }
    }

    /**
     * Synchronously invokes the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.IsSupportedProvider"&gt;IsSupportedProvider()&lt;/link&gt; D-Bus method on {@code proxy.} The calling thread is blocked until a reply is received.
     * <p>
     * See goa_manager_call_is_supported_provider() for the asynchronous version of this method.
     *
     * @param argProviderType Argument to pass with the method invocation.
     * @param outIsSupported Return location for return parameter or {@code null} to ignore.
     * @param cancellable A {@code GCancellable} or {@code null}.
     * @return {@code true} if the call succeeded, {@code false} if {@code error} is set.
     * @throws GErrorException see {@link org.gnome.glib.GError}
     */
    default boolean callIsSupportedProviderSync(String argProviderType,
            @Nullable Out<Boolean> outIsSupported, @Nullable Cancellable cancellable) throws
            GErrorException {
        try (var _arena = Arena.ofConfined()) {
            MemorySegment _outIsSupportedPointer = _arena.allocateFrom(
                    ValueLayout.JAVA_INT, Interop.toBoolean(outIsSupported) ? 1 : 0);
            MemorySegment _gerror = _arena.allocate(ValueLayout.ADDRESS);
            int _result;
            try {
                _result = (int) ManagerMethodHandles.goa_manager_call_is_supported_provider_sync.invokeExact(
                        handle(), 
                        (MemorySegment) (argProviderType == null ? MemorySegment.NULL : Interop.allocateNativeString(argProviderType, _arena)), 
                        (MemorySegment) (outIsSupported == null ? MemorySegment.NULL : _outIsSupportedPointer), 
                        (MemorySegment) (cancellable == null ? MemorySegment.NULL : cancellable.handle()), _gerror);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
            if (GErrorException.isErrorSet(_gerror)) {
                throw new GErrorException(_gerror);
            }
            if (outIsSupported != null) {
                outIsSupported.set(_outIsSupportedPointer.get(ValueLayout.JAVA_INT, 0) != 0);
            }
            boolean _returnValue = _result != 0;
            return _returnValue;
        }
    }

    /**
     * Helper function used in service implementations to finish handling invocations of the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.AddAccount"&gt;AddAccount()&lt;/link&gt; D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
     * <p>
     * This method will free {@code invocation,} you cannot use it afterwards.
     *
     * @param invocation A {@code GDBusMethodInvocation}.
     * @param accountObjectPath Parameter to return.
     */
    default void completeAddAccount(DBusMethodInvocation invocation, String accountObjectPath) {
        try (var _arena = Arena.ofConfined()) {
            if (invocation instanceof GObject _gobject) {
                _gobject.ref();
            }
            try {
                ManagerMethodHandles.goa_manager_complete_add_account.invokeExact(handle(), 
                        (MemorySegment) (invocation == null ? MemorySegment.NULL : invocation.handle()), 
                        (MemorySegment) (accountObjectPath == null ? MemorySegment.NULL : Interop.allocateNativeString(accountObjectPath, _arena)));
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
        }
    }

    /**
     * Helper function used in service implementations to finish handling invocations of the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.IsSupportedProvider"&gt;IsSupportedProvider()&lt;/link&gt; D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
     * <p>
     * This method will free {@code invocation,} you cannot use it afterwards.
     *
     * @param invocation A {@code GDBusMethodInvocation}.
     * @param isSupported Parameter to return.
     */
    default void completeIsSupportedProvider(DBusMethodInvocation invocation, boolean isSupported) {
        if (invocation instanceof GObject _gobject) {
            _gobject.ref();
        }
        try {
            ManagerMethodHandles.goa_manager_complete_is_supported_provider.invokeExact(handle(), 
                    (MemorySegment) (invocation == null ? MemorySegment.NULL : invocation.handle()), 
                    isSupported ? 1 : 0);
        } catch (Throwable _err) {
            throw new AssertionError(_err);
        }
    }

    /**
     * Signal emitted when a remote caller is invoking the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.AddAccount"&gt;AddAccount()&lt;/link&gt; D-Bus method.
     * <p>
     * If a signal handler returns {@code true}, it means the signal handler will handle the invocation (e.g. take a reference to {@code invocation} and eventually call goa_manager_complete_add_account() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the {@link org.gnome.gio.DBusError#UNKNOWN_METHOD} error is returned.
     *
     * @param handler the signal handler
     * @return a signal handler ID to keep track of the signal connection
     * @see HandleAddAccountCallback#run
     */
    default SignalConnection<HandleAddAccountCallback> onHandleAddAccount(
            HandleAddAccountCallback handler) {
        try (Arena _arena = Arena.ofConfined()) {
            try {
                var _name = Interop.allocateNativeString("handle-add-account", _arena);
                var _callbackArena = Arena.ofShared();
                var _result = (int) (long) Signals.g_signal_connect_data.invokeExact(handle(),
                        _name, handler.toCallback(_callbackArena),
                        Arenas.cacheArena(_callbackArena), Arenas.CLOSE_CB_SYM, 0);
                return new SignalConnection<>(handle(), _result);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
        }
    }

    /**
     * Emits the "handle-add-account" signal. See {@link #onHandleAddAccount}.
     */
    default boolean emitHandleAddAccount(DBusMethodInvocation invocation, String argProvider,
            String argIdentity, String argPresentationIdentity, Variant argCredentials,
            Variant argDetails) {
        try (Arena _arena = Arena.ofConfined()) {
            MemorySegment _result = _arena.allocate(ValueLayout.JAVA_INT);
            MemorySegment _name = Interop.allocateNativeString("handle-add-account", _arena);
            Object[] _args = new Object[] {
                    (MemorySegment) (invocation == null ? MemorySegment.NULL : invocation.handle()), 
                    (MemorySegment) (argProvider == null ? MemorySegment.NULL : Interop.allocateNativeString(argProvider, _arena)), 
                    (MemorySegment) (argIdentity == null ? MemorySegment.NULL : Interop.allocateNativeString(argIdentity, _arena)), 
                    (MemorySegment) (argPresentationIdentity == null ? MemorySegment.NULL : Interop.allocateNativeString(argPresentationIdentity, _arena)), 
                    (MemorySegment) (argCredentials == null ? MemorySegment.NULL : argCredentials.handle()), 
                    (MemorySegment) (argDetails == null ? MemorySegment.NULL : argDetails.handle()), _result};
            Signals.g_signal_emit_by_name.invokeExact(handle(), _name, _args);
            return _result.get(ValueLayout.JAVA_INT, 0) != 0;
        } catch (Throwable _err) {
            throw new AssertionError(_err);
        }
    }

    /**
     * Signal emitted when a remote caller is invoking the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.IsSupportedProvider"&gt;IsSupportedProvider()&lt;/link&gt; D-Bus method.
     * <p>
     * If a signal handler returns {@code true}, it means the signal handler will handle the invocation (e.g. take a reference to {@code invocation} and eventually call goa_manager_complete_is_supported_provider() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the {@link org.gnome.gio.DBusError#UNKNOWN_METHOD} error is returned.
     *
     * @param handler the signal handler
     * @return a signal handler ID to keep track of the signal connection
     * @see HandleIsSupportedProviderCallback#run
     */
    default SignalConnection<HandleIsSupportedProviderCallback> onHandleIsSupportedProvider(
            HandleIsSupportedProviderCallback handler) {
        try (Arena _arena = Arena.ofConfined()) {
            try {
                var _name = Interop.allocateNativeString("handle-is-supported-provider", _arena);
                var _callbackArena = Arena.ofShared();
                var _result = (int) (long) Signals.g_signal_connect_data.invokeExact(handle(),
                        _name, handler.toCallback(_callbackArena),
                        Arenas.cacheArena(_callbackArena), Arenas.CLOSE_CB_SYM, 0);
                return new SignalConnection<>(handle(), _result);
            } catch (Throwable _err) {
                throw new AssertionError(_err);
            }
        }
    }

    /**
     * Emits the "handle-is-supported-provider" signal. See {@link #onHandleIsSupportedProvider}.
     */
    default boolean emitHandleIsSupportedProvider(DBusMethodInvocation invocation,
            String argProviderType) {
        try (Arena _arena = Arena.ofConfined()) {
            MemorySegment _result = _arena.allocate(ValueLayout.JAVA_INT);
            MemorySegment _name = Interop.allocateNativeString("handle-is-supported-provider", _arena);
            Object[] _args = new Object[] {
                    (MemorySegment) (invocation == null ? MemorySegment.NULL : invocation.handle()), 
                    (MemorySegment) (argProviderType == null ? MemorySegment.NULL : Interop.allocateNativeString(argProviderType, _arena)), _result};
            Signals.g_signal_emit_by_name.invokeExact(handle(), _name, _args);
            return _result.get(ValueLayout.JAVA_INT, 0) != 0;
        } catch (Throwable _err) {
            throw new AssertionError(_err);
        }
    }

    /**
     * The Manager$Impl type represents a native instance of the Manager interface.
     */
    class Manager$Impl extends GObject implements Manager {
        static {
            Goa.javagi$ensureInitialized();
        }

        /**
         * Creates a new instance of Manager for the provided memory address.
         *
         * @param address the memory address of the instance
         */
        public Manager$Impl(MemorySegment address) {
            super(address);
        }
    }

    /**
     * Functional interface declaration of the {@code HandleAddAccountCallback} callback.
     * <p>
     * @see HandleAddAccountCallback#run
     */
    @FunctionalInterface
    interface HandleAddAccountCallback extends FunctionPointer {
        /**
         * Signal emitted when a remote caller is invoking the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.AddAccount"&gt;AddAccount()&lt;/link&gt; D-Bus method.
         * <p>
         * If a signal handler returns {@code true}, it means the signal handler will handle the invocation (e.g. take a reference to {@code invocation} and eventually call goa_manager_complete_add_account() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the {@link org.gnome.gio.DBusError#UNKNOWN_METHOD} error is returned.
         */
        boolean run(DBusMethodInvocation invocation, String argProvider, String argIdentity,
                String argPresentationIdentity, Variant argCredentials, Variant argDetails);

        /**
         * The {@code upcall} method is called from native code. The parameters
         * are marshaled and {@link #run} is executed.
         */
        default int upcall(MemorySegment sourceManager, MemorySegment invocation,
                MemorySegment argProvider, MemorySegment argIdentity,
                MemorySegment argPresentationIdentity, MemorySegment argCredentials,
                MemorySegment argDetails) {
            try {
                Arena _arena = Arena.ofAuto();
                var _invocationCached = (DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new);
                if (_invocationCached instanceof GObject _gobject) {
                    _gobject.ref();
                }
                var _result = run((DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new), Interop.getStringFrom(argProvider, TransferOwnership.NONE), Interop.getStringFrom(argIdentity, TransferOwnership.NONE), Interop.getStringFrom(argPresentationIdentity, TransferOwnership.NONE), MemorySegment.NULL.equals(argCredentials) ? null : new Variant(argCredentials), MemorySegment.NULL.equals(argDetails) ? null : new Variant(argDetails));
                return _result ? 1 : 0;
            } catch (Throwable _t) {
                GLib.log(Constants.LOG_DOMAIN, LogLevelFlags.LEVEL_WARNING, _t.toString() + " in HandleAddAccountCallback");
                return 0;
            }
        }

        /**
         * Creates a native function pointer to the {@link #upcall} method.
         *
         * @param arena the arena in which the function pointer is allocated
         * @return the native function pointer
         */
        default MemorySegment toCallback(Arena arena) {
            FunctionDescriptor _fdesc = FunctionDescriptor.of(ValueLayout.JAVA_INT,
                    ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                    ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                    ValueLayout.ADDRESS);
            MethodHandle _handle = Interop.upcallHandle(MethodHandles.lookup(), HandleAddAccountCallback.class, _fdesc);
            return Linker.nativeLinker().upcallStub(_handle.bindTo(this), _fdesc, arena);
        }
    }

    /**
     * Functional interface declaration of the {@code HandleIsSupportedProviderCallback} callback.
     * <p>
     * @see HandleIsSupportedProviderCallback#run
     */
    @FunctionalInterface
    interface HandleIsSupportedProviderCallback extends FunctionPointer {
        /**
         * Signal emitted when a remote caller is invoking the &lt;link linkend="gdbus-method-org-gnome-OnlineAccounts-Manager.IsSupportedProvider"&gt;IsSupportedProvider()&lt;/link&gt; D-Bus method.
         * <p>
         * If a signal handler returns {@code true}, it means the signal handler will handle the invocation (e.g. take a reference to {@code invocation} and eventually call goa_manager_complete_is_supported_provider() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the {@link org.gnome.gio.DBusError#UNKNOWN_METHOD} error is returned.
         */
        boolean run(DBusMethodInvocation invocation, String argProviderType);

        /**
         * The {@code upcall} method is called from native code. The parameters
         * are marshaled and {@link #run} is executed.
         */
        default int upcall(MemorySegment sourceManager, MemorySegment invocation,
                MemorySegment argProviderType) {
            try {
                Arena _arena = Arena.ofAuto();
                var _invocationCached = (DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new);
                if (_invocationCached instanceof GObject _gobject) {
                    _gobject.ref();
                }
                var _result = run((DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new), Interop.getStringFrom(argProviderType, TransferOwnership.NONE));
                return _result ? 1 : 0;
            } catch (Throwable _t) {
                GLib.log(Constants.LOG_DOMAIN, LogLevelFlags.LEVEL_WARNING, _t.toString() + " in HandleIsSupportedProviderCallback");
                return 0;
            }
        }

        /**
         * Creates a native function pointer to the {@link #upcall} method.
         *
         * @param arena the arena in which the function pointer is allocated
         * @return the native function pointer
         */
        default MemorySegment toCallback(Arena arena) {
            FunctionDescriptor _fdesc = FunctionDescriptor.of(ValueLayout.JAVA_INT,
                    ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS);
            MethodHandle _handle = Interop.upcallHandle(MethodHandles.lookup(), HandleIsSupportedProviderCallback.class, _fdesc);
            return Linker.nativeLinker().upcallStub(_handle.bindTo(this), _fdesc, arena);
        }
    }

    /**
     * Virtual table for the D-Bus interface &lt;link linkend="gdbus-interface-org-gnome-OnlineAccounts-Manager.top_of_page"&gt;org.gnome.OnlineAccounts.Manager&lt;/link&gt;.
     */
    class ManagerIface extends TypeInterface {
        private Method _handleAddAccountMethod;

        private Method _handleIsSupportedProviderMethod;

        /**
         * Create a ManagerIface proxy instance for the provided memory address.
         *
         * @param address the memory address of the native object
         */
        public ManagerIface(MemorySegment address) {
            super(Interop.reinterpret(address, getMemoryLayout().byteSize()));
        }

        /**
         * The memory layout of the native struct.
         *
         * @return the memory layout
         */
        public static MemoryLayout getMemoryLayout() {
            return MemoryLayout.structLayout(
                TypeInterface.getMemoryLayout().withName("parent_iface"),
                ValueLayout.ADDRESS.withName("handle_add_account"),
                ValueLayout.ADDRESS.withName("handle_is_supported_provider")
            ).withName("GoaManagerIface");
        }

        /**
         * Override virtual method {@code handle_add_account}.
         *
         * @param method the method to invoke
         */
        public void overrideHandleAddAccount(Arena arena, Method method) {
            this._handleAddAccountMethod = method;
            FunctionDescriptor _fdesc = FunctionDescriptor.of(ValueLayout.JAVA_INT,
                    ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                    ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS,
                    ValueLayout.ADDRESS);
            MethodHandle _handle = Interop.upcallHandle(MethodHandles.lookup(), ManagerIface.class, "handleAddAccountUpcall", _fdesc);
            MemorySegment _address = Linker.nativeLinker().upcallStub(_handle.bindTo(this), _fdesc, arena);
            getMemoryLayout().varHandle(MemoryLayout.PathElement.groupElement("handle_add_account"))
                    .set(handle(), 0, (method == null ? MemorySegment.NULL : _address));
        }

        private int handleAddAccountUpcall(MemorySegment object, MemorySegment invocation,
                MemorySegment argProvider, MemorySegment argIdentity,
                MemorySegment argPresentationIdentity, MemorySegment argCredentials,
                MemorySegment argDetails) {
            try {
                Arena _arena = Arena.ofAuto();
                var _objectCached = (Manager) InstanceCache.getForType(object, Manager$Impl::new);
                if (_objectCached instanceof GObject _gobject) {
                    _gobject.ref();
                }
                var _invocationCached = (DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new);
                if (_invocationCached instanceof GObject _gobject) {
                    _gobject.ref();
                }
                var _result = (boolean) this._handleAddAccountMethod.invoke((Manager) InstanceCache.getForType(object, Manager$Impl::new), (DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new), Interop.getStringFrom(argProvider, TransferOwnership.NONE), Interop.getStringFrom(argIdentity, TransferOwnership.NONE), Interop.getStringFrom(argPresentationIdentity, TransferOwnership.NONE), MemorySegment.NULL.equals(argCredentials) ? null : new Variant(argCredentials), MemorySegment.NULL.equals(argDetails) ? null : new Variant(argDetails));
                return _result ? 1 : 0;
            } catch (InvocationTargetException _ite) {
                GLib.log(Constants.LOG_DOMAIN, LogLevelFlags.LEVEL_WARNING, _ite.getCause().toString() + " in _handleAddAccountMethod");
                return 0;
            } catch (Throwable _t) {
                GLib.log(Constants.LOG_DOMAIN, LogLevelFlags.LEVEL_WARNING, _t.toString() + " in _handleAddAccountMethod");
                return 0;
            }
        }

        /**
         * Override virtual method {@code handle_is_supported_provider}.
         *
         * @param method the method to invoke
         */
        public void overrideHandleIsSupportedProvider(Arena arena, Method method) {
            this._handleIsSupportedProviderMethod = method;
            FunctionDescriptor _fdesc = FunctionDescriptor.of(ValueLayout.JAVA_INT,
                    ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS);
            MethodHandle _handle = Interop.upcallHandle(MethodHandles.lookup(), ManagerIface.class, "handleIsSupportedProviderUpcall", _fdesc);
            MemorySegment _address = Linker.nativeLinker().upcallStub(_handle.bindTo(this), _fdesc, arena);
            getMemoryLayout().varHandle(MemoryLayout.PathElement.groupElement("handle_is_supported_provider"))
                    .set(handle(), 0, (method == null ? MemorySegment.NULL : _address));
        }

        private int handleIsSupportedProviderUpcall(MemorySegment object, MemorySegment invocation,
                MemorySegment argProviderType) {
            try {
                Arena _arena = Arena.ofAuto();
                var _objectCached = (Manager) InstanceCache.getForType(object, Manager$Impl::new);
                if (_objectCached instanceof GObject _gobject) {
                    _gobject.ref();
                }
                var _invocationCached = (DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new);
                if (_invocationCached instanceof GObject _gobject) {
                    _gobject.ref();
                }
                var _result = (boolean) this._handleIsSupportedProviderMethod.invoke((Manager) InstanceCache.getForType(object, Manager$Impl::new), (DBusMethodInvocation) InstanceCache.getForType(invocation, DBusMethodInvocation::new), Interop.getStringFrom(argProviderType, TransferOwnership.NONE));
                return _result ? 1 : 0;
            } catch (InvocationTargetException _ite) {
                GLib.log(Constants.LOG_DOMAIN, LogLevelFlags.LEVEL_WARNING, _ite.getCause().toString() + " in _handleIsSupportedProviderMethod");
                return 0;
            } catch (Throwable _t) {
                GLib.log(Constants.LOG_DOMAIN, LogLevelFlags.LEVEL_WARNING, _t.toString() + " in _handleIsSupportedProviderMethod");
                return 0;
            }
        }
    }
}
