// This file was automatically generated by Java-GI. Do not edit this file
// directly! Visit <https://github.com/jwharm/java-gi/> for more information.
//
// The API documentation in this file was derived from GObject-Introspection
// metadata and may include text or comments from the original C sources.
//
// Copyright (c), upstream authors as identified in the GObject-Introspection
// metadata.
//
// This generated file is distributed under the same license as the original
// GObject-Introspection data, unless otherwise specified. Users of this file
// are responsible for complying with any licenses or terms required by the
// original authors.
//
// THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
//
package goa;

import io.github.jwharm.javagi.gobject.InstanceCache;
import io.github.jwharm.javagi.gobject.types.TypeCache;
import io.github.jwharm.javagi.interop.Interop;
import java.lang.foreign.Arena;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import javax.annotation.processing.Generated;
import org.gnome.gio.DBusInterface;
import org.gnome.gio.DBusInterfaceSkeleton;
import org.gnome.glib.Type;
import org.gnome.gobject.GObject;
import org.gnome.gobject.Value;

/**
 * The {@code GoaOAuthBasedSkeleton} structure contains only private data and should only be accessed using the provided API.
 */
@Generated("io.github.jwharm.JavaGI")
public class OAuthBasedSkeleton extends DBusInterfaceSkeleton implements DBusInterface, OAuthBased {
    static {
        Goa.javagi$ensureInitialized();
    }

    /**
     * Create a OAuthBasedSkeleton proxy instance for the provided memory address.
     *
     * @param address the memory address of the native object
     */
    public OAuthBasedSkeleton(MemorySegment address) {
        super(Interop.reinterpret(address, getMemoryLayout().byteSize()));
    }

    /**
     * Creates a new OAuthBasedSkeleton.
     */
    public OAuthBasedSkeleton() {
        super((MemorySegment) null);
        InstanceCache.newGObject(this, TypeCache.getType(this.getClass()), getMemoryLayout().byteSize(), (Object[]) null);
    }

    /**
     * Get the GType of the OAuthBasedSkeleton class
     *
     * @return the GType
     */
    public static Type getType() {
        return Interop.getType("goa_oauth_based_skeleton_get_type");
    }

    /**
     * The memory layout of the native struct.
     * @return the memory layout
     */
    public static MemoryLayout getMemoryLayout() {
        return MemoryLayout.structLayout(
            DBusInterfaceSkeleton.getMemoryLayout().withName("parent_instance"),
            ValueLayout.ADDRESS.withName("priv")
        ).withName("GoaOAuthBasedSkeleton");
    }

    /**
     * Returns this instance as if it were its parent type. This is mostly
     * synonymous to the Java {@code super} keyword, but will set the native
     * typeclass function pointers to the parent type. When overriding a native
     * virtual method in Java, "chaining up" with {@code super.methodName()}
     * doesn't work, because it invokes the overridden function pointer again.
     * To chain up, call {@code asParent().methodName()}. This will call the
     * native function pointer of this virtual method in the typeclass of the
     * parent type.
     */
    protected OAuthBasedSkeleton asParent() {
        OAuthBasedSkeleton _parent = new OAuthBasedSkeleton(handle());
        _parent.callParent(true);
        return _parent;
    }

    /**
     * A {@link Builder} object constructs a {@code OAuthBasedSkeleton}
     * with the specified properties.
     * Use the various {@code set...()} methods to set properties,
     * and finish construction with {@link Builder#build()}.
     */
    public static Builder<? extends Builder> builder() {
        return new Builder<>();
    }

    /**
     * Class structure for {@code GoaOAuthBasedSkeleton}.
     */
    public static class OAuthBasedSkeletonClass extends DBusInterfaceSkeleton.DBusInterfaceSkeletonClass {
        /**
         * Create a OAuthBasedSkeletonClass proxy instance for the provided memory address.
         *
         * @param address the memory address of the native object
         */
        public OAuthBasedSkeletonClass(MemorySegment address) {
            super(Interop.reinterpret(address, getMemoryLayout().byteSize()));
        }

        /**
         * Allocate a new OAuthBasedSkeletonClass.
         *
         * @param arena to control the memory allocation scope
         */
        public OAuthBasedSkeletonClass(Arena arena) {
            super(arena.allocate(getMemoryLayout()));
        }

        /**
         * Allocate a new OAuthBasedSkeletonClass.
         * The memory is allocated with {@link Arena#ofAuto}.
         */
        public OAuthBasedSkeletonClass() {
            super(Arena.ofAuto().allocate(getMemoryLayout()));
        }

        /**
         * The memory layout of the native struct.
         * @return the memory layout
         */
        public static MemoryLayout getMemoryLayout() {
            return MemoryLayout.structLayout(
                DBusInterfaceSkeleton.DBusInterfaceSkeletonClass.getMemoryLayout().withName("parent_class")
            ).withName("GoaOAuthBasedSkeletonClass");
        }
    }

    /**
     * Inner class implementing a builder pattern to construct a GObject with
     * properties.
     *
     * @param <B> the type of the Builder that is returned
     */
    public static class Builder<B extends Builder<B>> extends DBusInterfaceSkeleton.Builder<B> implements OAuthBased.Builder<B> {
        /**
         * Default constructor for a {@code Builder} object.
         */
        protected Builder() {
        }

        /**
         * Finish building the {@code OAuthBasedSkeleton} object. This will call
         * {@link GObject#withProperties} to create a new GObject instance,
         * which is then cast to {@code OAuthBasedSkeleton}.
         *
         * @return a new instance of {@code OAuthBasedSkeleton} with the properties
         *         that were set in the Builder object.
         */
        public OAuthBasedSkeleton build() {
            try {
                var _instance = (OAuthBasedSkeleton) GObject.withProperties(OAuthBasedSkeleton.getType(), getNames(), getValues());
                connectSignals(_instance.handle());
                return _instance;
            } finally {
                for (Value _value : getValues()) _value.unset();
                getArena().close();
            }
        }
    }
}
